### ISSUE TITLE
Move indicator improvements

### ISSUE THREAD

**Issue by Defetyre** [Friedhof5rb/EschersGambit#8]
Make the move indicator that appears when you select a piece change depending on what kind of move you can make with it:
Blue for a move on an empty square, red for taking a piece (and indicating what pieces participated in checkmate), yellow to indicate a selected piece, and pink or green for castling.
Also, remove the arrows and instead make some kind of light ornament for them.
Previous turn indicator would be nice too
Examples:
![Снимок](https://github.com/Friedhof5rb/SpaceBlockChess/assets/88449275/964b9079-4b56-4a9f-bb26-aa8975919a36)
![mate](https://github.com/Friedhof5rb/SpaceBlockChess/assets/88449275/eb2c24ca-58fa-4b5c-8f75-4b425b71e6b0)

**Comment by Friedhof5rb** [comment]
Alright, I can change the Colours of the Move Indicator but I would either want to avoid the Colours Pink and Yellow for the Background or change the Colours of the Yellow and Pink Pieces, because I think there should be some Contrast.
I would also want to avoid making the Pieces Green, because then the Green Dot for 2+ Pawns, Castle Kings and Castle Rooks would be hard to see. This is a Problem already for selected Pieces with a green dot.

I can replace the Arrows with some decoration if you want.
Also currently there is no Check or Checkmate, you just take the King.
I could implement some highlighters for what would be checkmate, however this is gonna take some time, as I would need to code finding possible Moves first, something I wanted to do any ways to verify the Moves made, as currently any selected Piece can move to any square that is highlighted for Capture. Practically this is no Problem, because your Opponent would see if you try to cheat by using some Move_Highlighter, but in theory the other Approach would be better.

I can absolutely add previous turn indicators.
If you have any Suggestions on how to solve the Problems with the Colours, please let me know.

**Comment by Friedhof5rb** [comment]
Maybe make the Pieces a different shade of Green and Red?

**Comment by Defetyre** [comment]
You can also just make the indicators transparent. Kind of like Stained glass panes in the base game

**Comment by Friedhof5rb** [comment]
Yeah that is Possible, I will look closer into what Colours to use for the Rest.

**Comment by Friedhof5rb** [comment]
Alright, I have added Chat-Messages to indicate Checkmate and Check and Stalemate also.
I am probably not going to do special highlighting for Pieces that participated in Checkmate, as I think this feature with the Chat and the torches achieve roughly the same thing. But I am still going to leave this open for now, in case you want to give me further feedback. If there is none I am going to close this after some time.

**Comment by Defetyre** [comment]
Sounds would be nice too, if it's possible.

**Comment by Friedhof5rb** [comment]
Ok I have added Sounds
